# Generated by Django 6.0 on 2026-01-01 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_task_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='last-update'),
        ),
    ]
